### ISSUE TITLE
关于数据库数据类型的设计

### ISSUE THREAD

**Issue by bunnyxt** [cgDeepLearn/BilibiliCrawler#2]
<img width="514" alt="qq20190306-122636 2x" src="https://user-images.githubusercontent.com/32478279/53856039-333d8b00-400b-11e9-8b31-c584cde83951.png">
这里，aid，mid，tid，view这种获得的只是数字的字段为什么设计成字符串类型？

**Comment by cgDeepLearn** [comment]
> <img alt="qq20190306-122636 2x" width="514" src="https://user-images.githubusercontent.com/32478279/53856039-333d8b00-400b-11e9-8b31-c584cde83951.png">
> 
> 这里，aid，mid，tid，view这种获得的只是数字的字段为什么设计成字符串类型？

当时从b站接口取数据好像是字符串,也没多想,确实应该存int型
